export const SET_LOADING = 'SET_LOADING'
export const SET_FRIENDS = 'SET_FRIENDS'
export const UPDATE_FRIEND_SUCCESS = 'UPDATE_FRIEND_SUCCESS'
export const UPDATE_FRIEND_ERROR = 'UPDATE_FRIEND_ERROR'
export const UPDATE_FRIEND_BEGIN = 'UPDATE_FRIEND_BEGIN'

export const GET_FRIENDS_SUCCESS = 'GET_FRIENDS_SUCCESS'
export const GET_FRIENDS_ERROR = 'GET_FRIENDS_ERROR'
export const GET_FRIENDS_BEGIN = 'GET_FRIENDS_BEGIN'

export const DELETE_FRIEND_SUCCESS = 'DELETE_FRIEND_SUCCESS'
export const DELETE_FRIEND_ERROR = 'DELETE_FRIEND_ERROR'
export const DELETE_FRIEND_BEGIN = 'DELETE_FRIEND_BEGIN'

export const ADD_FRIEND_BEGIN = 'ADD_FRIEND_BEGIN'
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS'
export const ADD_FRIEND_ERROR = 'ADD_FRIEND_ERROR'
